apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: redis
  labels:
    app: redis
spec:
  clusterIP: None
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: master
      protocol: TCP
    - name: redis-sentinel
      port: 26379
      targetPort: sentinel
      protocol: TCP
